# Banks, Accounts and Customer
BANK_ID	= 0
# Banks
BANK_CODE = 1
FULL_NAME = 2
LOGO = 3
WEBSITE = 4
BANKS_BANK_ROUTING_SCHEME = 5
BANKS_BANK_ROUTING_ADDRESS = 6
LIST_OF_ATTRIBUTE_NAMES_AND_VALUES = 7
# Accounts
PRODUCT_CODE = 1
CUSTOMER_OWNER_IDS = 2
OWNERSHIP_TYPE = 3
ACCOUNT_STATUS = 4
ISSUE_DATE = 5
LAST_MOVEMENT_DATE = 6
BALANCE	= 7
ACCOUNTS_CURRENCY = 8
LABEL = 9
ACCOUNTS_BANK_ROUTING_SCHEME = 10
ACCOUNTS_BANK_ROUTING_ADDRESS = 11
ACCOUNT_ROUTING_SCHEME = 12
ACCOUNT_ROUTING_ADDRESS = 13
BRANCH_ROUTING_SCHEME = 14
BRANCH_ROUTING_ADDRESS = 15
ACCOUNT_ATTRIBUTES_LIST = 16
# Transactions
TRANSACTION_ID = 0
INITIATING_PARTY = 1
DEBTOR_LEGAL_NAME = 2
DEBTOR_BANK_ROUTING_SCHEME = 3
DEBTOR_BANK_ROUTING_ADDRESS	= 4
DEBTOR_ACCOUNT_ROUTING_SCHEME = 5
DEBTOR_ACCOUNT_ROUTING_ADDRESS = 6
CREDITOR_LEGAL_NAME = 7
CREDITOR_BANK_ROUTING_SCHEME = 8
CREDITOR_BANK_ROUTING_ADDRESS = 9
CREDITOR_ACCOUNT_ROUTING_SCHEME = 10
CREDITOR_ACCOUNT_ROUTING_ADDRESS = 11
AMOUNT = 12
TRANSACTIONS_CURRENCY = 13
DESCRIPTION = 14
BOOKED_DATE	= 15
VALUE_DATE = 16
TRANSACTION_ATTRIBUTES_LIST = 17
# Customers
CUSTOMER_NUMBER = 1
LEGAL_NAME = 2
MOBILE_PHONE_NUMBER = 3
EMAIL = 4
DATE_OF_BIRTH = 5
TITLE = 6
BRANCH_ID = 7
NAME_SUFFIX = 8
CUSTOMER_ATTRIBUTES_LIST = 9

